service: investment-roka-backend
frameworkVersion: '3'
app: investment-roka-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  logRetentionInDays: 7
  memorySize: 128
  architecture: arm64
  environment:
    ROKA_TABLE_NAME: table-${self:app}-${self:provider.stage}
    ROKA_SECONDARY_INDEX_GSI1: GSI1
    ROKA_SECONDARY_INDEX_GSI2: GSI2
    ROKA_SECONDARY_INDEX_GSI3: GSI3




custom:
  ApiUrl: ${self:provider.stage}/v1
  ServiceName: ${self:app}

plugins:
  - serverless-prune-plugin
  - serverless-plugin-custom-roles
  - serverless-offline

resources:
  - ${file(./config/resources/table.yml)}


functions:
  - ${file(./config/lambdas/crud.yml)}
  - ${file(./config/lambdas/email.yml)}





package:
  individually: true
  patterns:
    - "!node_modules/**"

