name: branch notification

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  notify:
    name: Notify on branch push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send notification to webhook
      env:
        BRANCH_NAME: ${{ github.ref }}
        USER: ${{ github.actor }}
        REPO_URL: https://github.com/${{ github.repository }}/tree/${{ github.ref }}
      run: |
        curl -X POST "${{ vars.GOOGLECHAT_URL }}" \
        -H "Content-Type: application/json" \
        -d "{\"text\": \"Hola, hemos detectado que el usuario $USER ha agregado nuevos cambios a la rama $BRANCH_NAME. Revisala en el repositorio $REPO_URL\"}"
