name: Aprendiendo GitHub actions
run-name: ¡Estoy Aprendiendo GitHubactions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: definir variable
        run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV
      - name: correr script
        run: python hola_mundo.py
