name: Push from develop by admins
run-name: ¡Push Admin!
on:
  push:
    branches:
      - develop
jobs:
  push-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install awscli
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Instalar AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Autenticar con AWS
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

      - name: Construir y desplegar
        run: |
          npm install
          npm run deploy

      - name: Enviar notificación a Google Chat
        if: always()
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            curl -X POST "${{ vars.GOOGLECHAT_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ github.repository }} - Se ha hecho un despliegue en el entorno de desarrollo con éxito,user  = "${{ github.actor }}". Ver resultado: ${{ github.run_id }}\"}"
          else
            curl -X POST "${{ secrets.GOOGLECHAT_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ github.repository }} - Hubo un error al desplegar en el entorno de desarrollo , user = "${{ github.actor }}". Ver resultado: ${{ github.run_id }}\"}"
          fi



