name: Validate Branches

on:
  push:
    branches:
      - '*'

jobs:
  validate-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Check branch name
      run: |
        BRANCH=$(echo $GITHUB_REF | awk -F/ '{print $3}')
        if [[ ! $BRANCH =~ ^(feature|hotfix)/.*$ ]]; then
          echo "Error: Branch name must start with 'feature/' or 'hotfix/'."
          exit 1
        fi
